#!/usr/bin/env ruby

puts "Before pushing to remote we need a backup of your working database\n"
puts "Be sure mysqldump is in your $PATH or this will fail\n"
puts "Enter database name:"
db = gets.chomp
puts "Enter mysql host:"
host = gets.chomp
puts "Enter user:"
user = gets.chomp
cmd = "mysqldump --add-drop-table -h #{host} -u #{user} -p #{db} > ../db_export.sql"
wasGood = system(cmd)
if wasGood
  puts "Great that worked. Now lets run a few git commands and push to remote\n"
  puts "Enter your commit message:"
  commit = gets.chomp
  system('cd ..')
  system("git add . && git commit -a -m '#{commit}'")
  exec("git push origin master")
  exec(cmd)
else
  puts "Failed for whatever reason. Check that you can run mysqldump manually like so:\nmysqldump --add-drop-table -h #{host} -u #{user} -p #{db} > ../db_export.sql"
end

